### ISSUE TITLE
Recommendations for padding?

### ISSUE THREAD

**Issue by mike-lawrence** [onnela-lab/gptools#1]
Just started exploring this work/package, and I'm a little uncertain as to best practices for padding. First, do I understand the examples correctly that only one side needs to be padded? Second, is there any general guidance on how much padding to add?

**Comment by tillahoffmann** [comment]
Thanks for the interest, @mike-lawrence. I've added an example to the documentation in #2, and you can see a preview of the documentation [here](https://gptools-stan--2.org.readthedocs.build/en/2/docs/padding/padding.html).

> First, do I understand the examples correctly that only one side needs to be padded?

I've only ever padded on the right. In principle, padding anywhere should be fine because of the circular boundary conditions, but I've not yet tried it.

> Second, is there any general guidance on how much padding to add?

The amount of padding required depends somewhat on the kernel that's being used. As a rule of thumb for squared exponential kernels, three times the expected correlation length should do a good job. The example linked above provides a more in-depth discussion.
