### ISSUE TITLE
Consider running SBC for the paper

### ISSUE THREAD

**Issue by mike-lawrence** [onnela-lab/gptools#7]
Probably not the correct venue for this feedback, but I've been playing with data simulated from a vanilla GP then fitting using the FFT-based methods in gptools to check a crude measure of calibration, and it strikes me that a full check using [SBC](https://github.com/hyunjimoon/SBC) might be considered for use in your [paper](http://arxiv.org/abs/2301.08836). Given the fact that the FFT model isn't expected to be precisely equivalen to the vanilla model, the check shouldn't be expected to pass, but the ways in which it fails could be informative for advising users on where inference should be considered more or less reliable given the approximations.

**Comment by tillahoffmann** [comment]
Yes, that's a nice idea to check the effect of the sparse approximation and periodic boundary conditions for FFT methods. We've already run a bunch of simulations (sample from the prior and draw posterior samples) to generate the runtime scaling figures (fig. 2). Adding SBC may not be too much work given that the simulations already exist.

**Comment by tillahoffmann** [comment]
Thanks for the suggestion. I've had a more thorough look at SBC for the Fourier methods and how it relates to padding as you pointed out in #1. In particular, I simulated data under the standard Gaussian process model (the benchmark model in eq. (2) in the preprint), i.e.,

$$
\begin{aligned}
    \vec{f}&\sim\mathsf{MultivariateNormal}\left(0, K\right)\\
    \vec{y}&\sim\mathsf{Normal}\left(\vec{f}, \kappa^2\right),
\end{aligned}
$$

where $K$ is the kernel covariance and $\kappa^2$ is observation noise variance.

I fitted both the true generative model (where we expect SBC checks to pass unless I added a bug) and the Fourier method with varying amounts of padding. For each fit, I held out the last data point because it is most affected by periodic boundary conditions (the first would also have done the job). Here's the setup.

```python
# Number of synthetic datasets.
m = 100
# Number of observations to generate per dataset.
n = 128
# Length scale of the kernel. Chosen to be large-ish to exacerbate the effect of 
# periodic boundary conditions. Observations are spaced on an integer grid.
length_scale = 16
# Marginal amplitude of the kernel.
sigma = 1
# Observation noise scale--somewhat arbitrary choice.
kappa = 1
```

Panel (a) in the figure below shows an example realization (GP as a line, data as a scatter) with seed picked to make the two ends of the GP be far apart, i.e., a bad-case scenario. Panel (c) shows the posterior mean for both the exact model (blue) and various amounts of padding (other colors). Padding $w$ is reported as the ratio of padding to kernel length scale $\ell$. As expected, the orange curve (no padding) is severely affected by the periodic boundary conditions because it must be continuous across the boundary. But introducing about one kernel length scale worth of padding seems to almost eliminate the effect. Panel (b) formalizes the evaluation somewhat. We evaluate the log posterior density for the latent GP $f_n$ whose corresponding observation $y_n$ was held out, i.e., $p\left(f_n \mid y_{1},\ldots,y_{n-1}\right)$. Values are averaged over synthetic datasets, and error bars are standard errors. The horizontal line is the log posterior obtained by fitting the true generative model. The results are consistent with our initial eye-balling: the posterior density obtained using Fourier methods with padding is indistinguishable from the true model once $w/\ell>1$. Panel (d) shows the same results but for a Matern 3/2 kernel. I expected that slightly larger padding is required for Matern 3/2 kernels because they have heavier tails, but it appears padding with one correlation length also does the trick.

![image](https://user-images.githubusercontent.com/966348/219263654-2b105162-bb40-40e3-a5ac-fdcfde4daf5e.png)

So far so good, but the above is of course not SBC. I also evaluated the rank of the true $f_n$ amongst the posterior samples, and we expect the ranks to be uniformly distributed. Because we want to investigate calibration as a function of $w$, looking at histograms can be difficult. Here, I used the Kolmogorov-Smirnov test to evaluate the p-value that the data were generated by a uniform distribution. The results are shown in the table below rounded to three significant digits.

| padding factor $w/\ell$ | ExpQuadKernel | Matern32Kernel |
| - | - | - |
| exact | 0.851 | 0.217 |
| 0 | 0.000 | 0.000 |
| 0.125 | 0.000 | 0.000 |
| 0.25 | 0.000 | 0.001 |
| 0.375 | 0.001 | 0.018 |
| 0.5 | 0.002 | 0.058 |
| 0.75 | 0.096 | 0.220 |
| 1.0 | 0.347 | 0.320 |
| 1.25 | 0.787 | 0.088 |
| 1.5 | 0.770 | 0.143 |

For small amounts of padding, we can very confidently reject the null hypothesis that the ranks are uniformly distributed. Once we reach $w/\ell>1$ the ranks are not inconsistent with a uniform distribution.

To make a long story short, one correlation length is probably fine, and we're pretty safe with two. The details are in #10. I'll incorporate your suggestion of SBC into the next version of the preprint (with proper acknowledgment of course).

---

SBC is a little more fiddly for the sparse approximation because the "decision space" is very large. For Fourier methods, we only need to choose the amount of padding, but for the sparse approximation we can choose an arbitrary dependency structure. 

This decision space can be reduced by considering only nearest-neighbor methods, but results may still be sensitive to other factors such as the sampling density. E.g., for a given kernel length scale, we may require a large number of neighbors if the sampling density is high (because they would all depend on each other if we considered the full model). In contrast, if the sampling density is low, we may be able to get away with only a few neighbors because the full covariance matrix is naturally sparse-ish. A hand-wavy argument, of course.
